online_dlg = [
    "Sir, I am online and ready",
    "Sir, I am online",
    "I am online, sir",
    "Sir, my status is online",
    "I am online, sir, happy to assist you",
    "Sir, I am now online",
    "I am online and ready to help, sir",
    "Sir, I have gone online",
    "Sir, I am online, awaiting your command",
    "Sir, I am online and at your service",
    "Online and ready, sir",
    "I am online and here to assist, sir",
    "Sir, I am now online and ready",
    "Sir, I am online and ready to serve",
    "Sir, I am online and operational",
    "Sir, I have gone online and am ready to assist",
    "Sir, I am online and available",
    "Online and at your service, sir",
    "Sir, I am online and prepared to help",
    "Sir, I am online and standing by",
    "Sir, I am online, how can I assist?",
    "Sir, I am online and awaiting your instructions",
    "Sir, I am now online, how can I help?",
    "Sir, I am online and ready for your commands",
    "Sir, I am online and ready to take your orders",
    "Sir, I am online and ready for duty",
    "Online and ready to assist, sir",
    "Sir, I am online, what do you need?",
    "Sir, I am online, how can I serve you?",
    "Sir, I am online and at your disposal",
    "Sir, I am online, what can I do for you?",
    "Sir, I am online, ready and waiting",
    "Sir, I am online and ready to go",
    "Sir, I am online and ready to support you",
    "Sir, I am online, your command is my wish",
    "Sir, I am online and ready for action",
    "Sir, I am online, ready to serve",
    "Sir, I am online and here to help",
    "Sir, I am online, how can I be of assistance?",
    "Sir, I am online, how may I assist you?",
    "Sir, I am online and at your service, awaiting commands",
    "Sir, I am online and ready to execute your commands",
    "Sir, I am online and ready to perform tasks",
    "Sir, I am online and ready to assist with any tasks",
    "Sir, I am online and ready to aid you",
    "Sir, I am online and ready to handle your requests",
    "Sir, I am online and here to serve you",
    "Sir, I am online and at your command",
    "Sir, I am online and awaiting your requests",
    "Sir, I am online and ready for instructions",
    "Sir, I am online and prepared to assist with any task",
    "Sir, I am online and ready to follow your orders",
    "Sir, I am online and prepared to serve",
    "Sir, I am online, ready to assist",
    "Sir, I am online and ready to support",
    "Sir, I am online, here to help",
    "Sir, I am online and ready to execute orders",
    "Sir, I am online and ready for your instructions",
    "Sir, I am online and ready to provide assistance",
    "Sir, I am online and awaiting your commands",
    "Sir, I am online and here to aid you",
    "Sir, I am online and ready for your tasks",
    "Sir, I am online and ready for any commands",
    "Sir, I am online and ready to work",
    "Sir, I am online and ready to be of service",
    "Sir, I am online and at your disposal, ready to help",
    "Sir, I am online and ready to take on tasks",
    "Sir, I am online and prepared to assist in any way",
    "Sir, I am online and ready to fulfill your requests",
    "Sir, I am online and ready to help you",
    "Sir, I am online and prepared for your instructions",
    "Sir, I am online and ready to follow your lead",
    "Sir, I am online and at your beck and call",
    "Sir, I am online and ready to serve you",
    "Sir, I am online and ready to assist with any requests",
    "Sir, I am online and ready to follow your commands",
    "Sir, I am online and here to assist with anything",
    "Sir, I am online and ready for any task",
    "Sir, I am online and ready for your guidance",
    "Sir, I am online and ready to assist you in any way",
    "Sir, I am online and ready to perform",
    "Sir, I am online and at your service, ready to help",
    "Sir, I am online and ready for any instructions",
    "Sir, I am online and ready to assist with all tasks",
    "Sir, I am online and prepared for any requests",
    "Sir, I am online and ready to take on any task",
    "Sir, I am online and ready for your directions",
    "Sir, I am online and ready to assist with whatever you need",
    "Sir, I am online and ready to serve your needs",
    "Sir, I am online and ready to execute your tasks",
    "Sir, I am online and ready to be at your service",
    "Sir, I am online and ready to assist in any tasks",
    "Sir, I am online and ready to perform any duty",
    "Sir, I am online and prepared to assist you",
    "Sir, I am online and ready for your requests",
    "Sir, I am online and ready for any duty",
    "Sir, I am online and ready to fulfill any request",
]
offline_dlg = [
    "Sir, I am offline. Please connect to the WiFi or internet",
    "Sir, I am currently offline. Please check the internet connection",
    "I am offline, sir. Kindly connect me to the internet",
    "Sir, my status is offline. Please ensure I am connected to the network",
    "I am offline, sir. Please establish an internet connection",
    "Sir, I am offline. Please connect me to the internet",
    "Sir, I am offline. Kindly check the network connection",
    "Sir, I am offline. Please reconnect me to the WiFi",
    "Sir, I am offline. A network connection is required",
    "Sir, I am offline. Please connect to the internet",
    "Offline, sir. Please check the WiFi connection",
    "Sir, I am offline. Internet connection needed",
    "Sir, I am offline. Please verify the internet connection",
    "Sir, I am offline. Network connection required",
    "Sir, I am offline. Please reconnect to the internet",
    "Sir, I am offline. WiFi connection needed",
    "Sir, I am offline. Please ensure network connectivity",
    "Offline status, sir. Please connect to the WiFi",
    "Sir, I am offline. Please verify the network connection",
    "Sir, I am offline. Internet access required",
    "Sir, I am offline. Please check the internet connection",
    "Sir, I am offline. Please ensure a stable network connection",
    "Sir, I am offline. Please reconnect to the network",
    "Sir, I am offline. A WiFi connection is needed",
    "Sir, I am offline. Internet connection is necessary",
    "Sir, I am offline. Please check WiFi or internet",
    "Sir, I am offline. Network access required",
    "Sir, I am offline. Please establish a connection to the internet",
    "Sir, I am offline. Internet connection needed",
    "Sir, I am offline. Please connect me to the network",
    "Sir, I am offline. Please ensure internet connectivity",
    "Sir, I am offline. Network connection needed",
    "Sir, I am offline. Please verify internet access",
    "Sir, I am offline. Please connect to WiFi",
    "Sir, I am offline. Please ensure a network connection",
    "Sir, I am offline. Please connect me to the WiFi",
    "Sir, I am offline. Please reconnect to the internet",
    "Sir, I am offline. Please check the network connection",
    "Sir, I am offline. WiFi connection required",
    "Sir, I am offline. Network connectivity is needed",
    "Sir, I am offline. Internet access required",
    "Sir, I am offline. Please ensure a stable internet connection",
    "Sir, I am offline. Please connect to the network",
    "Sir, I am offline. Internet connection required",
    "Sir, I am offline. Please establish a network connection",
    "Sir, I am offline. Please reconnect to the WiFi",
    "Sir, I am offline. Please ensure a stable WiFi connection",
    "Sir, I am offline. Network access needed",
    "Sir, I am offline. Please connect to the internet",
    "Sir, I am offline. WiFi access required",
    "Sir, I am offline. Please ensure network access",
    "Sir, I am offline. Please check the WiFi connection",
    "Sir, I am offline. Please ensure an internet connection",
    "Sir, I am offline. Network connection required",
    "Sir, I am offline. Internet connection needed",
    "Sir, I am offline. Please connect me to the network",
    "Sir, I am offline. Please ensure internet access",
    "Sir, I am offline. Network connectivity required",
    "Sir, I am offline. Please check the network connection",
    "Sir, I am offline. Please reconnect to the WiFi",
    "Sir, I am offline. Internet connectivity required",
    "Sir, I am offline. Network access needed",
    "Sir, I am offline. Please verify the internet connection",
    "Sir, I am offline. WiFi connection needed",
    "Sir, I am offline. Please check the internet access",
    "Sir, I am offline. Please ensure a WiFi connection",
    "Sir, I am offline. Please reconnect to the network",
    "Sir, I am offline. Internet access needed",
    "Sir, I am offline. Network connection is required",
    "Sir, I am offline. Please connect to the WiFi",
    "Sir, I am offline. Please ensure internet connectivity",
    "Sir, I am offline. Network access required",
    "Sir, I am offline. Please verify network connection",
    "Sir, I am offline. Please check the WiFi connection",
    "Sir, I am offline. Internet connection required",
    "Sir, I am offline. Network connection needed",
    "Sir, I am offline. Please connect to the internet",
    "Sir, I am offline. Please ensure network access",
    "Sir, I am offline. Please check the network connectivity",
    "Sir, I am offline. Please reconnect to the internet",
    "Sir, I am offline. Internet access required",
    "Sir, I am offline. Please ensure a network connection",
    "Sir, I am offline. Please verify internet connection",
    "Sir, I am offline. Please check the WiFi or internet connection",
    "Sir, I am offline. Network connection required",
    "Sir, I am offline. Please reconnect to the network",
    "Sir, I am offline. Please connect to WiFi or internet",
    "Sir, I am offline. Please ensure WiFi access",
    "Sir, I am offline. Internet connection is needed",
    "Sir, I am offline. Please check WiFi or internet access",
    "Sir, I am offline. Please establish network connectivity",
]
yt_search = [
    "Sure, I’ll check YouTube for you!",
    "Alright! Let me find that on YouTube.",
    "Searching YouTube as requested.",
    "Let me pull up YouTube and get that for you.",
    "Looking up your request on YouTube!",
    "Heading to YouTube to search that for you.",
    "Sure, I’ll take a look on YouTube.",
    "Just a moment while I search YouTube.",
    "YouTube search in progress!",
    "Finding that video on YouTube!",
    "One moment, let’s see what YouTube has.",
    "Checking YouTube for results!",
    "I’ll look up that query on YouTube.",
    "Let’s see what YouTube says!",
    "Okay, let’s check YouTube!",
    "I’ll do a quick YouTube search.",
    "Hang tight, searching YouTube now.",
    "Finding some YouTube options for you.",
    "On it! Checking YouTube now.",
    "Sure thing! I’ll pull up YouTube.",
    "Looking up that topic on YouTube.",
    "One second, searching on YouTube for you.",
    "Just a moment, checking YouTube.",
    "I’ll see if YouTube has anything relevant.",
    "Going to YouTube for you!",
    "Checking for YouTube videos now.",
    "Give me a moment to look on YouTube.",
    "Let’s search that on YouTube.",
    "Let’s see what we find on YouTube!",
    "Hold on, YouTube search coming up!",
    "I’m on it! Searching YouTube.",
    "Finding what YouTube has on that.",
    "I’ll take care of it on YouTube!",
    "Let me look that up on YouTube.",
    "Checking if YouTube has some good results.",
    "Looking that up on YouTube.",
    "Opening YouTube to find that for you!",
    "You got it! Searching YouTube.",
    "Let me do a quick YouTube check.",
    "Heading over to YouTube now.",
    "Let me see what YouTube has for this.",
    "YouTube search, coming up!",
    "Finding something for you on YouTube.",
    "Starting a YouTube search for you.",
    "Just a second, YouTube has it!",
    "Let me go through YouTube for you.",
    "I’ll check the latest on YouTube.",
    "Launching YouTube for your request.",
    "Checking YouTube right now.",
    "I’m diving into YouTube for that.",
    "Looking into YouTube for relevant videos.",
    "Starting a search on YouTube.",
    "Pulling up YouTube options.",
    "YouTube results coming soon!",
    "Give me a second to YouTube it!",
    "Looking that up now on YouTube.",
    "Quick YouTube search for you.",
    "Heading over to YouTube for more info.",
    "Finding some options on YouTube.",
    "I’ll YouTube that for you.",
    "Hold on, searching on YouTube.",
    "Seeing what’s available on YouTube.",
    "Alright, checking YouTube options!",
    "Pulling that up on YouTube.",
    "One second, let me find it on YouTube.",
    "Just a moment, I’ll YouTube that!",
    "Got it! Checking YouTube.",
    "I’ll look on YouTube for that.",
    "Let’s find a video on YouTube.",
    "Checking YouTube, one sec.",
    "I’ll see what’s trending on YouTube!",
    "Getting that YouTube video for you.",
    "Launching YouTube search.",
    "Looking through YouTube for options.",
    "Let’s get on YouTube for you.",
    "I’ll grab that from YouTube.",
    "Starting the YouTube search.",
    "I’ll see what YouTube suggests.",
    "Let me find something useful on YouTube.",
    "YouTube has plenty to offer, searching!",
    "Let’s pull up a YouTube video.",
    "Hold tight, YouTube results soon.",
    "Checking for the latest on YouTube.",
    "Exploring YouTube for you.",
    "Sure, let’s YouTube that.",
    "I’ll get the best from YouTube.",
    "YouTube has lots! Let’s see.",
    "Let’s find that YouTube video.",
    "YouTube is on it!",
    "Let’s see what’s on YouTube.",
    "Checking YouTube’s best results.",
    "Starting YouTube query.",
    "Getting your request from YouTube.",
    "Pulling something from YouTube!",
    "Let’s see the latest on YouTube.",
    "Opening YouTube’s search.",
    "Let me dig through YouTube.",
    "Okay, I’ll take a look on YouTube.",
    "Just a moment, opening YouTube.",
    "Here’s what I found on YouTube.",
    "Loading up YouTube now."
]
search_comp = [
    "Here’s what I found on YouTube for you!",
    "I’ve got the results from YouTube.",
    "All set! Here are some YouTube videos.",
    "Found some videos that match your query.",
    "Here are the best YouTube results I found.",
    "I’ve pulled up some options from YouTube!",
    "Here’s the video lineup from YouTube.",
    "Done! Check out these YouTube videos.",
    "I found a few good options on YouTube.",
    "Here’s the YouTube search result you asked for.",
    "I’ve gathered a list of YouTube videos for you.",
    "Got it! Here’s what YouTube has to offer.",
    "All done! These are from YouTube.",
    "Here are the most relevant YouTube results.",
    "Your search results from YouTube are ready.",
    "Found some interesting videos on YouTube!",
    "All set! Here’s what I found on YouTube.",
    "Take a look! Here’s the YouTube content.",
    "These YouTube videos might be just what you need!",
    "Here’s what YouTube has on this topic.",
    "I’ve got some YouTube recommendations for you.",
    "Here’s the YouTube list I found.",
    "Here are the top YouTube matches.",
    "YouTube search is complete! Here’s what I found.",
    "Take a look at these YouTube results.",
    "Here’s a summary of YouTube videos.",
    "I found some related videos on YouTube.",
    "Got it! These YouTube results should help.",
    "Here’s a selection from YouTube.",
    "These videos seem to match your search.",
    "All set with YouTube results!",
    "Here’s what YouTube suggests for this.",
    "Done searching! Here are some YouTube links.",
    "Here’s the list I got from YouTube.",
    "Take a look at these YouTube options.",
    "These videos might be just what you’re looking for!",
    "Finished! Here’s what YouTube offers.",
    "All done searching YouTube! Here are the results.",
    "Here’s the latest from YouTube.",
    "I found a collection of videos for you.",
    "YouTube search is ready—check these out!",
    "Done! I gathered these videos from YouTube.",
    "Here’s a set of videos from YouTube.",
    "All done with the search! Here’s what I found.",
    "These are the top videos I found.",
    "Found some popular YouTube videos for you!",
    "Done! Here’s the YouTube video lineup.",
    "I pulled up these videos for you!",
    "YouTube results ready—enjoy watching!",
    "Check out these videos I found on YouTube.",
    "Here’s the video list from YouTube!",
    "Finished gathering YouTube results!",
    "Found these videos—you might like them!",
    "Here’s what I could find on YouTube.",
    "Your search results from YouTube are here.",
    "I’ve got some recommendations from YouTube.",
    "Here’s what’s available on YouTube.",
    "Take a look at these YouTube video results.",
    "Done! These YouTube videos should be helpful.",
    "Here’s what YouTube suggests.",
    "These videos match your search.",
    "I gathered some YouTube content for you!",
    "Here are the YouTube videos I found.",
    "These results came up on YouTube!",
    "Here’s a YouTube playlist for you!",
    "Take a look at these options from YouTube.",
    "Here’s the content I found on YouTube.",
    "I found these on YouTube for you.",
    "Here’s what I gathered from YouTube.",
    "YouTube results are in—check them out!",
    "Here’s what I found, straight from YouTube.",
    "These videos should match your query!",
    "Found some good videos from YouTube.",
    "Here’s what’s trending on YouTube about it.",
    "Your YouTube results are ready!",
    "Done! Here are some videos you might like.",
    "I collected these from YouTube for you.",
    "Here’s what YouTube came up with.",
    "These are the YouTube results for your search.",
    "YouTube search complete! Here’s the result.",
    "Here are some videos related to your query.",
    "You’re all set! Here’s what YouTube has.",
    "I found a few things on YouTube!",
    "These YouTube videos look relevant.",
    "I’ve got some YouTube content for you.",
    "These videos are a match for your search.",
    "All set! These are the YouTube results.",
    "Here’s what I got from YouTube.",
    "YouTube search done—here’s the list!",
    "Done! Check out these videos on YouTube.",
    "Found these interesting YouTube videos for you!",
    "I’ve compiled a list of videos from YouTube.",
    "Here are some good matches on YouTube.",
    "Here’s the best of what YouTube has.",
    "Finished! These are the YouTube results.",
    "Done with the search! Here’s YouTube’s response.",
    "These should be helpful—YouTube search is done!",
    "YouTube has these videos on the topic.",
    "Here’s the YouTube search result!",
    "Done! Check out these YouTube finds."
]
play_song = [
    "Sure thing! Playing your song now.",
    "Alright, let’s get that song going!",
    "Starting the song for you!",
    "Here comes your requested tune!",
    "Got it! Enjoy your song.",
    "Playing your song now—hope you like it!",
    "Here’s your song, starting now!",
    "On it! Let the music play.",
    "Loading up your song now.",
    "I’ll play that song for you right away.",
    "Just a sec, playing your tune!",
    "Playing the requested track.",
    "Cueing up your song now!",
    "Here’s the music you asked for!",
    "Let’s get this song playing!",
    "Your song is starting now—enjoy!",
    "Time for some music! Here’s your song.",
    "Tune time! Starting it up for you.",
    "Got it! Playing your requested song.",
    "The song is coming right up!",
    "Playing that track for you now.",
    "Let’s get this track started!",
    "All set! Here’s the song.",
    "Playing your music now—enjoy!",
    "Your song’s on the way!"
]
google_search_responses = [
    "Sure! Let me look that up on Google for you.",
    "Alright, I’ll get some info from Google.",
    "Searching Google as requested!",
    "Let’s see what Google has to say about that.",
    "I’m on it! Checking Google now.",
    "Just a moment while I Google that for you.",
    "I’ll pull up some Google search results.",
    "One second—searching Google for you.",
    "Finding the info you need on Google!",
    "Let me find that on Google for you.",
    "I’ll have the Google results for you shortly.",
    "Starting a quick Google search now!",
    "Looking that up on Google—one moment.",
    "I’ll check Google for the latest information.",
    "Let’s see what Google can find.",
    "Pulling up some Google results for you!",
    "On it! Searching Google right now.",
    "I’ll gather some answers from Google.",
    "Checking Google to find the info you need.",
    "I’m on Google—search in progress!",
    "Let me gather the top results from Google.",
    "Finding the best information on Google!",
    "Searching for that on Google for you.",
    "Let’s see what’s available on Google.",
    "Google has a lot—let’s find the best results!"
]
search_comp_ggl = [
    "Here’s what I found from Google!",
    "I’ve got the Google search results for you.",
    "All done! Here’s what Google came up with.",
    "Here are the top Google results.",
    "Found some information on Google for you!",
    "Here’s what I could gather from Google.",
    "Here are the Google search results.",
    "Got it! Here’s what Google has to offer.",
    "All set! Here’s what I found on Google.",
    "Here’s a summary of the Google search results.",
    "Take a look at these results from Google.",
    "I’ve gathered some information from Google.",
    "Your Google search results are ready.",
    "Here’s the information I found on Google.",
    "Done searching! Here’s what Google provided.",
    "These are the top matches from Google.",
    "Here are some relevant Google search results.",
    "The Google results are ready—here you go!",
    "These are the best Google results I found.",
    "I found some helpful information on Google!",
    "Here’s what’s available on Google.",
    "Google has a few good results—check them out!",
    "Here’s a list of Google search results for you.",
    "The search is complete! Here’s what I found.",
    "I found a few things on Google that might help.",
    "Here’s what Google suggests for this query."
]
opening_dialogues = [
    "Hello! How can I help you today?",
    "Hi there! What can I assist you with?",
    "Good day! Ready to help you with anything.",
    "Hey! What would you like to do today?",
    "Hello! How can I make things easier for you?",
    "Greetings! How can I assist you right now?",
    "Hi! Is there something I can help with?",
    "Hello! I’m here to assist—what’s up?",
    "Good to see you! What can I do for you?",
    "Hi there! Need a hand with anything?",
    "Hello! Ready when you are!",
    "Hey! How can I be of assistance?",
    "Good day! Let’s tackle something together.",
    "Hi! How can I make your day easier?",
    "Greetings! Ready to assist!",
    "Hello! What do you have in mind?",
    "Hi there! Need some help?",
    "Good to see you! How can I assist?",
    "Hello! Here to help—just say the word.",
    "Hi! What would you like me to do?",
    "Hello! Need assistance with something?",
    "Good day! What can I help you with?",
    "Hey! What’s on the agenda?",
    "Hi there! I’m all ears.",
    "Hello! Ready to get started?",
    "Greetings! How can I make things easier?",
    "Hi! Let’s get to work—what’s up?",
    "Hello! What’s your request today?",
    "Good day! What can I look up for you?",
    "Hi! Need help finding something?",
    "Hello! How can I assist with today’s tasks?",
    "Hey! Let’s make things simpler—what’s up?",
    "Hello! Is there anything I can do for you?",
    "Good day! How can I assist your search?",
    "Hi there! Got something for me?",
    "Greetings! Let me know what you need.",
    "Hello! I’m here to lend a hand!",
    "Hey! Let’s accomplish something!",
    "Hello! Just let me know what you need!",
    "Hi! What’s on your to-do list?",
    "Hello! How can I assist today?",
    "Good day! I’m ready to help.",
    "Hi! Got any tasks for me?",
    "Hello! Ready to help with your queries!",
    "Greetings! How can I assist you now?",
    "Hey! How can I be useful today?",
    "Hi there! Got a request?",
    "Hello! Let’s get things done.",
    "Good day! What can I help you achieve?",
    "Hi! What are we working on today?",
    "Hello! Any questions I can answer?",
    "Greetings! What do you need assistance with?",
    "Hey! Here to make your day easier.",
    "Hi! What’s the first thing we’re tackling?",
    "Hello! How can I serve you today?",
    "Good day! What’s on your mind?",
    "Hi there! What can I find for you?",
    "Hello! How may I help you today?",
    "Hi! Is there something I can look up?",
    "Greetings! Let’s get started.",
    "Hello! Ready to assist with anything!",
    "Hey! Here to help you with your tasks.",
    "Hi there! What’s your first task?",
    "Good day! How can I support you today?",
    "Hello! Let’s get this done together.",
    "Hi! Got any questions for me?",
    "Hello! What would you like me to handle?",
    "Greetings! What can I assist with?",
    "Hey! Here to lend a hand.",
    "Hello! What’s the plan for today?",
    "Hi there! How can I make things easier?",
    "Hello! What’s on your list?",
    "Hi! How can I support you?",
    "Good day! Need any information?",
    "Hi there! What’s your first request?",
    "Hello! I’m here to make things simple.",
    "Hey! Got something for me to help with?",
    "Hello! What’s the task at hand?",
    "Greetings! Ready for your next task?",
    "Hi! Let me know how I can assist.",
    "Good day! What can I take care of?",
    "Hello! What would you like to start with?",
    "Hi! Here to help—what’s your request?",
    "Greetings! Got something specific in mind?",
    "Hello! How can I assist with your work?",
    "Hey! Let’s get things moving.",
    "Hello! Ready for action!",
    "Hi! Is there something I can find?",
    "Hello! Let me know what you need done.",
    "Good day! What can I help you find?",
    "Hi there! Let’s make things happen.",
    "Hello! Ready for your instructions.",
    "Hey! How can I be useful today?",
    "Hello! What’s your first request?",
    "Good day! I’m here to assist.",
    "Hi! Anything you need help with?",
    "Hello! Let’s get started on your tasks.",
    "Greetings! How can I make it easier?",
    "Hi! What would you like me to do?",
    "Hello! Ready to get started on anything?",
    "Good day! What’s your first task?",
    "Hi there! Let’s start!",
    "Hello! Here to support your work.",
    "Hey! What can I look up for you?",
    "Hi! Got a question? I’m ready.",
    "Hello! What can I handle for you?",
    "Greetings! Ready for anything you need.",
    "Hello! What’s the plan?",
    "Hi there! Let’s begin!",
    "Good day! What’s your first request?",
    "Hey! How can I be of service?",
    "Hello! How can I make things better?",
    "Hi! Here to assist with whatever you need.",
    "Hello! Ready to get things going?",
    "Good day! I’m here to help.",
    "Hi! Is there anything specific I can do?",
    "Hello! Ready for your commands.",
    "Hey! Need some info or assistance?",
    "Hello! Let’s accomplish your tasks.",
    "Greetings! What can I handle first?",
    "Hi! Let’s make things easier together.",
    "Hello! Here for all your queries.",
    "Good day! How can I be useful?",
    "Hi! What’s on your mind?",
    "Hello! Need any assistance?",
    "Hey! Let’s get to work.",
    "Hi! What can I start with?",
    "Hello! How can I help with your tasks?",
    "Greetings! I’m here for you.",
    "Hi there! What’s your first question?",
    "Hello! Ready for anything you need.",
    "Good day! How can I assist with that?",
    "Hi! What can I help you find?",
    "Hello! Here to assist in any way.",
    "Hey! Ready for your instructions.",
    "Hello! Let’s get things done today!",
    "Hi! Need a hand with anything specific?",
    "Good day! I’m all ears.",
    "Hi there! What’s up first?",
    "Hello! Ready to assist in every way.",
    "Hey! I’m here to help.",
    "Hello! Got any questions for me?",
    "Hi! Let’s tackle the task at hand.",
    "Hello! How can I support your tasks?",
    "Greetings! What’s your first inquiry?",
    "Hi! What would you like to work on?",
    "Hello! What’s on today’s agenda?",
    "Good day! Let’s get started!",
    "Hi! What can I look up or help with?",
    "Hello! What’s on your list?",
    "Hey! Ready to assist you!",
    "Hello! What are we working on?",
    "Hi! Ready when you are!",
    "Hello! Need help with anything?",
    "Good day! I’m ready to assist.",
    "Hi! How can I help make things easier?",
    "Hello! I’m here to help, anytime!",
    "Hey! Let’s tackle your tasks.",
    "Hello! How can I make it simpler for you?",
    "Greetings! Ready to get things done!",
    "Hi! Here for all your needs.",
    "Hello! Let me know what you need!",
    "Good day! What can I work on?",
    "Hi! I’m here to make things easier.",
    "Hello! Let’s start the task list.",
    "Hey! What’s first on your list?"
]
goodbye_dialogues = [
    "Goodbye! Take care and see you soon!",
    "Farewell! Wishing you all the best until we meet again.",
    "See you later! Don't be a stranger!",
    "Until next time! Stay safe and well.",
    "Take care! Looking forward to our next chat.",
    "Goodbye for now! Keep in touch!",
    "It’s been great! See you next time!",
    "Wishing you a wonderful day ahead! Goodbye!",
    "So long! Hope to catch up again soon.",
    "Adios! Have a fantastic day!",
    "Catch you later! Stay awesome!",
    "Until we meet again! Take care!",
    "Goodbye! Sending you positive vibes!",
    "See you soon! Have a great one!",
    "Take it easy! Looking forward to next time!",
    "Farewell! May your days be bright!",
    "Goodbye! Enjoy every moment!",
    "So long! Keep smiling!",
    "Until next time! Stay healthy!",
    "Take care! Can’t wait to hear from you!",
    "Goodbye! Keep shining!",
    "See you later! Have fun out there!",
    "Farewell! Remember to cherish every day!",
    "Adieu! Until we chat again!",
    "Goodbye! Keep in touch and stay safe!",
    "See you soon! Best wishes!"
]
alarm_dialogues = [
    "Got it! What time would you like me to set the alarm for?",
    "Sure! Please tell me the time for the alarm.",
    "Alarm setting in progress! What time should I set it for?",
    "I can help with that! Just let me know the time.",
    "Setting an alarm sounds great! What time do you want?",
    "Okay! Please specify the time you'd like the alarm to go off.",
    "Alarm? Absolutely! What time should I set it?",
    "I'm on it! What time would you like your alarm to ring?",
    "Sure thing! What time should I wake you up?",
    "Just let me know the time, and I'll set the alarm for you!"
]
reminder_dialogues = [
    "Your reminder alarm is set! Don't forget to take action.",
    "I've set the alarm for your task. You'll be alerted on time!",
    "Alarm is ready! You'll be reminded when it's time.",
    "I've set the alarm for your upcoming event. Stay on track!",
    "You're all set! The alarm will help you remember your schedule.",
    "Reminder alarm activated! You'll get a nudge when it's time.",
    "Your alert is set! Make sure to be prepared.",
    "The alarm is set for your important task. Good luck!",
    "I've scheduled the alarm. You'll be reminded shortly.",
    "Your alarm is ready! Let's make sure you don't miss anything important."
]