import pyautogui
from time import sleep
def set_alarm(t):
    pyautogui.press("win")
    sleep(1)
    pyautogui.typewrite("clock")
    sleep(1)
    pyautogui.press("enter")
    sleep(2)
    pyautogui.click(x=153, y=184)
    sleep(1)
    pyautogui.click(x=1847, y=1023)
    t = t.split(":")
    pyautogui.typewrite(t[0])
    pyautogui.press("tab")
    pyautogui.typewrite(t[1])
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("enter")
    sleep(1)
    pyautogui.hotkey("alt", "f4")